
name: Wade Huang
title: Wade Huang's Blogs
email: wadehuang36@gmail.com
description: > 
  A technology enthusiast. <br/>
  Expert at .Net, Nodejs, Angular and Android
selfie: /assets/images/wade.jpg
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  wadehuang36
link: https://www.linkedin.com/in/wadenhuang/

markdown: kramdown

disqus:
  shortname: wadehuang36

analytics-google: 'UA-101876196-1'

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
